# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b3db968118892a88a64344d60c8060d002f16c5cef288b0630d6b15f658ccfeeeb2add2bd0cef7c5de3292dd0d381c14dfdaefac039c78a99ad6b5255fb6a70

test:
  secret_key_base: c271f643971bec313490508439244970c400b77b671a1bfe8484c05269d655d8b2fae771a04809b5387b2f46401b1c308e9b062ba05ba6133819dde55c85f83e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
